openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /tasks:
    $ref: ./paths/tasks.yaml
  /tasks/{id}:
    $ref: ./paths/tasks-id.yaml
components:
  schemas:
    Task:
      $ref: ./components/schemas/Task.yaml
  responses:
    BadRequest:
      $ref: ./components/responses/BadRequest.yaml
    NotFound:
      $ref: ./components/responses/NotFound.yaml